package org.virus.l337;

import java.util.*;

/**
 *
 * @author virus
 */
public interface chars {

    // Basic leet characters
    Map<Character, List<Character>> basic_leet = Map.of(
            'o', Arrays.asList('0'),
            'i', Arrays.asList('1', '!'),
            'l', Arrays.asList('1', '!'),
            'r', Arrays.asList('2'),
            'e', Arrays.asList('3'),
            's', Arrays.asList('5', '$'),
            'b', Arrays.asList('6', '8'),
            't', Arrays.asList('7'),
            'g', Arrays.asList('9'),
            'a', Arrays.asList('@', '4')
    );

    // Moderate leet characters
    Map<Character, List<Character>> moderate_leet = Map.of(
            'c', Arrays.asList('(', ')'),
            'l', Arrays.asList('|'),
            'i', Arrays.asList('|'),
            'f', Arrays.asList('/', '\\'),
            't', Arrays.asList('+'),
            'a', Arrays.asList('*')
    );

    // Advanced leet characters
    Map<Character, List<String>> advance_leet = Map.ofEntries(
            Map.entry('h', Arrays.asList("|-|")),
            Map.entry('u', Arrays.asList("|_|")),
            Map.entry('n', Arrays.asList("|\\|", "~", "/~\\")),
            Map.entry('w', Arrays.asList("|\\|\\", "/V\\")),
            Map.entry('r', Arrays.asList("|2")),
            Map.entry('e', Arrays.asList("|3")),
            Map.entry('a', Arrays.asList("|4", "/\\")),
            Map.entry('s', Arrays.asList("|5")),
            Map.entry('l', Arrays.asList("|7")),
            Map.entry('k', Arrays.asList("|<")),
            Map.entry('f', Arrays.asList("|=")),
            Map.entry('y', Arrays.asList("|>", "|?")),
            Map.entry('m', Arrays.asList("/_\\", "][\\//")),
            Map.entry('v', Arrays.asList("/|\\", "/^\\", "\\/")),
            Map.entry('d', Arrays.asList("\\|\\", "\\_\\")),
            Map.entry('x', Arrays.asList("}{", "><"))
    );

    // Currency leet characters
    Map<Character, List<Character>> currency_leet = Map.of(
            'c', Arrays.asList('¢'),
            'e', Arrays.asList('€'),
            's', Arrays.asList('$'),
            'y', Arrays.asList('¥'),
            'i', Arrays.asList('₹'),
            'l', Arrays.asList('£')
    );

    Map<String, List<String>> emoji_leet = Map.ofEntries(
            Map.entry("happy", Arrays.asList("😀")), 
            Map.entry("sad", Arrays.asList("😔")), 
            Map.entry("angry", Arrays.asList("😠")), 
            Map.entry("laugh", Arrays.asList("😂")), 
            Map.entry("cry", Arrays.asList("😭")), 
            Map.entry("confused", Arrays.asList("😕")), 
            Map.entry("surprised", Arrays.asList("😲")), 
            Map.entry("cool", Arrays.asList("😎")), 
            Map.entry("blush", Arrays.asList("😊")), 
            Map.entry("heart-eyes", Arrays.asList("😍")), 
            Map.entry("worried", Arrays.asList("😟")), 
            Map.entry("facepalm", Arrays.asList("🤦♂")), 
            Map.entry("sleepy", Arrays.asList("😴")), 
            Map.entry("sick", Arrays.asList("🤒")), 
            Map.entry("nerd", Arrays.asList("🤓")), 
            Map.entry("crazy", Arrays.asList("🤪")), 
            Map.entry("shocked", Arrays.asList("😱")), 
            Map.entry("flirt", Arrays.asList("😘")), 
            Map.entry("irritated", Arrays.asList("😒")), 
            Map.entry("excited", Arrays.asList("🤩")), 
            Map.entry("silly", Arrays.asList("🤡")), 
            Map.entry("dead", Arrays.asList("💀")), 
            Map.entry("alien", Arrays.asList("👽")), 
            Map.entry("ghost", Arrays.asList("👻")), 
            Map.entry("robot", Arrays.asList("🤖")), 
            Map.entry("clown", Arrays.asList("🤡")), 
            Map.entry("poop", Arrays.asList("💩")), 
            Map.entry("money", Arrays.asList("💰")), 
            Map.entry("fire", Arrays.asList("🔥")), 
            Map.entry("thumbs-up", Arrays.asList("👍")), 
            Map.entry("thumbs-down", Arrays.asList("👎")), 
            Map.entry("muscle", Arrays.asList("💪")), 
            Map.entry("broken-heart", Arrays.asList("💔")), 
            Map.entry("heart", Arrays.asList("❤")), 
            Map.entry("rainbow", Arrays.asList("🌈")), 
            Map.entry("sun", Arrays.asList("☀")), 
            Map.entry("moon", Arrays.asList("🌙")), 
            Map.entry("star", Arrays.asList("⭐")), 
            Map.entry("flower", Arrays.asList("🌸")), 
            Map.entry("pizza", Arrays.asList("🍕")), 
            Map.entry("hamburger", Arrays.asList("🍔")), 
            Map.entry("beer", Arrays.asList("🍺")), 
            Map.entry("cocktail", Arrays.asList("🍸")), 
            Map.entry("coffee", Arrays.asList("☕")), 
            Map.entry("book", Arrays.asList("📖")), 
            Map.entry("computer", Arrays.asList("💻")), 
            Map.entry("phone", Arrays.asList("📱")), 
            Map.entry("tv", Arrays.asList("📺")), 
            Map.entry("watch", Arrays.asList("⌚")), 
            Map.entry("car", Arrays.asList("🚗")), 
            Map.entry("plane", Arrays.asList("✈")), 
            Map.entry("rocket", Arrays.asList("🚀")), 
            Map.entry("football", Arrays.asList("⚽")), 
            Map.entry("basketball", Arrays.asList("🏀")), 
            Map.entry("tennis", Arrays.asList("🎾")), 
            Map.entry("music", Arrays.asList("🎵")), 
            Map.entry("guitar", Arrays.asList("🎸")), 
            Map.entry("drum", Arrays.asList("🥁")), 
            Map.entry("microphone", Arrays.asList("🎤")), 
            Map.entry("movie", Arrays.asList("🎥")), 
            Map.entry("camera", Arrays.asList("📷")), 
            Map.entry("gift", Arrays.asList("🎁")), 
            Map.entry("balloon", Arrays.asList("🎈")), 
            Map.entry("party", Arrays.asList("🎉")), 
            Map.entry("christmas-tree", Arrays.asList("🎄")), 
            Map.entry("fireworks", Arrays.asList("🎆")), 
            Map.entry("flag", Arrays.asList("🎌")), 
            Map.entry("pencil", Arrays.asList("✏")), 
            Map.entry("paintbrush", Arrays.asList("🖌")), 
            Map.entry("scissors", Arrays.asList("✂")), 
            Map.entry("paperclip", Arrays.asList("📎")), 
            Map.entry("lock", Arrays.asList("🔒")), 
            Map.entry("key", Arrays.asList("🔑")), 
            Map.entry("lightbulb", Arrays.asList("💡")), 
            Map.entry("battery", Arrays.asList("🔋")), 
            Map.entry("clock", Arrays.asList("🕰")), 
            Map.entry("stopwatch", Arrays.asList("⏱")), 
            Map.entry("hourglass", Arrays.asList("⏳")), 
            Map.entry("magnifying-glass", Arrays.asList("🔍")), 
            Map.entry("microscope", Arrays.asList("🔬")), 
            Map.entry("telescope", Arrays.asList("🔭")), 
            Map.entry("umbrella", Arrays.asList("☔")), 
            Map.entry("toilet", Arrays.asList("🚽")), 
            Map.entry("shower", Arrays.asList("🚿")), 
            Map.entry("bathtub", Arrays.asList("🛁")), 
            Map.entry("bed", Arrays.asList("🛌")), 
            Map.entry("couch", Arrays.asList("🛋")), 
            Map.entry("chair", Arrays.asList("🪑")), 
            Map.entry("lamp", Arrays.asList("💡")), 
            Map.entry("door", Arrays.asList("🚪")), 
            Map.entry("window", Arrays.asList("🪟")), 
            Map.entry("plant", Arrays.asList("🌿")), 
            Map.entry("tree", Arrays.asList("🌳")), 
            Map.entry("cloud", Arrays.asList("☁")), 
            Map.entry("sunrise", Arrays.asList("🌅")), 
            Map.entry("sunset", Arrays.asList("🌇")), 
            Map.entry("mountain", Arrays.asList("⛰")), 
            Map.entry("beach", Arrays.asList("🏖")), 
            Map.entry("island", Arrays.asList("🏝")), 
            Map.entry("desert", Arrays.asList("🏜")), 
            Map.entry("city", Arrays.asList("🏙")), 
            Map.entry("night-sky", Arrays.asList("🌃")), 
            Map.entry("fire-engine", Arrays.asList("🚒")), 
            Map.entry("police-car", Arrays.asList("🚓")), 
            Map.entry("ambulance", Arrays.asList("🚑")), 
            Map.entry("construction", Arrays.asList("🚧")), 
            Map.entry("traffic-light", Arrays.asList("🚦")), 
            Map.entry("railway-car", Arrays.asList("🚃")), 
            Map.entry("train", Arrays.asList("🚂")), 
            Map.entry("metro", Arrays.asList("🚇")), 
            Map.entry("bus", Arrays.asList("🚌")), 
            Map.entry("taxi", Arrays.asList("🚕")), 
            Map.entry("truck", Arrays.asList("🚚")), 
            Map.entry("ship", Arrays.asList("🚢")), 
            Map.entry("airplane", Arrays.asList("✈")), 
            Map.entry("helicopter", Arrays.asList("🚁")), 
            Map.entry("motorcycle", Arrays.asList("🏍")), 
            Map.entry("bicycle", Arrays.asList("🚲"))
    );
}
