class chars {
    // Basic leet characters
    val basicLeet = mapOf(
        "o" to listOf("0"),
        "i" to listOf("1", "!"),
        "l" to listOf("1", "!"),
        "r" to listOf("2"),
        "e" to listOf("3"),
        "s" to listOf("5", "$"),
        "b" to listOf("6", "8"),
        "t" to listOf("7"),
        "g" to listOf("9"),
        "a" to listOf("@", "4")
    )

    // Moderate leet characters
    val moderateLeet = mapOf(
        "c" to listOf("(", ")"),
        "l" to listOf("|"),
        "i" to listOf("|"),
        "f" to listOf("/", "\\"),
        "t" to listOf("+"),
        "a" to listOf("*"),
    )

    // Advanced leet characters
    val advancedLeet = mapOf(
        "h" to listOf("|-|"),
        "u" to listOf("|_|"),
        "n" to listOf("|\\|", "~", "/~\\"),
        "w" to listOf("|\\|\\", "/V\\"),
        "r" to listOf("|2"),
        "e" to listOf("|3"),
        "a" to listOf("|4", "/\\"),
        "s" to listOf("|5"),
        "l" to listOf("|7"),
        "k" to listOf("|<"),
        "f" to listOf("|="),
        "y" to listOf("|>", "|?"),
        "m" to listOf("/_\\", "][\\//"),
        "v" to listOf("/|\\", "/^\\", "\\/"),
        "d" to listOf("\\|\\", "\\_\\"),
        "x" to listOf("}{", "><"),
    )

    // Currency leet characters
    val currencyLeet = mapOf(
        "c" to listOf("¢"),
        "e" to listOf("€"),
        "s" to listOf("$"),
        "y" to listOf("¥"),
        "i" to listOf("₹"),
        "l" to listOf("£")
    )

    // emoji leet characters
    val emojiLeet = mapOf(
        "happy" to listOf("😀"),
        "sad" to listOf("😔"),
        "angry" to listOf("😠"),
        "laugh" to listOf("😂"),
        "cry" to listOf("😭"),
        "confused" to listOf("😕"),
        "surprised" to listOf("😲"),
        "cool" to listOf("😎"),
        "blush" to listOf("😊"),
        "heart-eyes" to listOf("😍"),
        "worried" to listOf("😟"),
        "facepalm" to listOf("🤦♂"),
        "sleepy" to listOf("😴"),
        "sick" to listOf("🤒"),
        "nerd" to listOf("🤓"),
        "crazy" to listOf("🤪"),
        "shocked" to listOf("😱"),
        "flirt" to listOf("😘"),
        "irritated" to listOf("😒"),
        "excited" to listOf("🤩"),
        "silly" to listOf("🤡"),
        "dead" to listOf("💀"),
        "alien" to listOf("👽"),
        "ghost" to listOf("👻"),
        "robot" to listOf("🤖"),
        "clown" to listOf("🤡"),
        "poop" to listOf("💩"),
        "money" to listOf("💰"),
        "fire" to listOf("🔥"),
        "thumbs-up" to listOf("👍"),
        "thumbs-down" to listOf("👎"),
        "muscle" to listOf("💪"),
        "broken-heart" to listOf("💔"),
        "heart" to listOf("❤"),
        "rainbow" to listOf("🌈"),
        "sun" to listOf("☀"),
        "moon" to listOf("🌙"),
        "star" to listOf("⭐"),
        "flower" to listOf("🌸"),
        "pizza" to listOf("🍕"),
        "hamburger" to listOf("🍔"),
        "beer" to listOf("🍺"),
        "cocktail" to listOf("🍸"),
        "coffee" to listOf("☕"),
        "book" to listOf("📖"),
        "computer" to listOf("💻"),
        "phone" to listOf("📱"),
        "tv" to listOf("📺"),
        "watch" to listOf("⌚"),
        "car" to listOf("🚗"),
        "plane" to listOf("✈"),
        "rocket" to listOf("🚀"),
        "football" to listOf("⚽"),
        "basketball" to listOf("🏀"),
        "tennis" to listOf("🎾"),
        "music" to listOf("🎵"),
        "guitar" to listOf("🎸"),
        "drum" to listOf("🥁"),
        "microphone" to listOf("🎤"),
        "movie" to listOf("🎥"),
        "camera" to listOf("📷"),
        "gift" to listOf("🎁"),
        "balloon" to listOf("🎈"),
        "party" to listOf("🎉"),
        "christmas-tree" to listOf("🎄"),
        "fireworks" to listOf("🎆"),
        "flag" to listOf("🎌"),
        "pencil" to listOf("✏"),
        "paintbrush" to listOf("🖌"),
        "scissors" to listOf("✂"),
        "paperclip" to listOf("📎"),
        "lock" to listOf("🔒"),
        "key" to listOf("🔑"),
        "lightbulb" to listOf("💡"),
        "battery" to listOf("🔋"),
        "clock" to listOf("🕰"),
        "stopwatch" to listOf("⏱"),
        "hourglass" to listOf("⏳"),
        "magnifying-glass" to listOf("🔍"),
        "microscope" to listOf("🔬"),
        "telescope" to listOf("🔭"),
        "umbrella" to listOf("☔"),
        "toilet" to listOf("🚽"),
        "shower" to listOf("🚿"),
        "bathtub" to listOf("🛁"),
        "bed" to listOf("🛌"),
        "couch" to listOf("🛋"),
        "chair" to listOf("🪑"),
        "lamp" to listOf("💡"),
        "door" to listOf("🚪"),
        "window" to listOf("🪟"),
        "plant" to listOf("🌿"),
        "tree" to listOf("🌳"),
        "cloud" to listOf("☁"),
        "sunrise" to listOf("🌅"),
        "sunset" to listOf("🌇"),
        "mountain" to listOf("⛰"),
        "beach" to listOf("🏖"),
        "island" to listOf("🏝"),
        "desert" to listOf("🏜"),
        "city" to listOf("🏙"),
        "night-sky" to listOf("🌃"),
        "fire-engine" to listOf("🚒"),
        "police-car" to listOf("🚓"),
        "ambulance" to listOf("🚑"),
        "construction" to listOf("🚧"),
        "traffic-light" to listOf("🚦"),
        "railway-car" to listOf("🚃"),
        "train" to listOf("🚂"),
        "metro" to listOf("🚇"),
        "bus" to listOf("🚌"),
        "taxi" to listOf("🚕"),
        "truck" to listOf("🚚"),
        "ship" to listOf("🚢"),
        "airplane" to listOf("✈"),
        "helicopter" to listOf("🚁"),
        "motorcycle" to listOf("🏍"),
        "bicycle" to listOf("🚲")
    )
}